streamlined intallation of openssl modules
PROD-74072

diff --git a/package/summit-fips-utils/fips-set b/package/summit-fips-utils/fips-set
--- a/package/summit-fips-utils/fips-set
+++ b/package/summit-fips-utils/fips-set
@@ -22,11 +22,8 @@ openssl_fipsinit() {
 
 	openssl fipsinstall -in /etc/ssl/fipsmodule.cnf \
 			-module /usr/lib/ossl-modules/fips.so \
-			-self_test_onload -verify -quiet
-	if [ $? -ne 0 ]; then
-		echo "ERROR: openssl-3 fips module verification failed"
-		return 1
-	fi
+			-self_test_onload -verify -quiet ||\
+		{ echo "ERROR: openssl-3 fips module verification failed" >&2; return 1; }
 	return 0
 }
 
@@ -35,27 +32,31 @@ warning() {
 }
 
 case "${1}" in
-  fips) ## set fips only
+  fips) 
+    # set fips only
     openssl_fipsinit || return 1
     fw_setenv fips_wifi  || return 1
     fw_setenv fips 1
     warning
     ;;
 
-  fips_wifi) ## set fips wifi
+  fips_wifi) 
+    # set fips wifi
     openssl_fipsinit || return 1
     fw_setenv fips 1  || return 1
     fw_setenv fips_wifi 1
     warning
     ;;
 
-  unset) ## unset
+  unset) 
+    # unset
     fw_setenv fips || return 1
     fw_setenv fips_wifi
     warning
     ;;
 
-  status) ## status
+  status) 
+    # status
     [ -f /proc/sys/crypto/fips_enabled ] && \
     [ -f /proc/sys/crypto/fips_wifi_enabled ] || \
     { echo "none"; return; }
@@ -75,6 +76,6 @@ case "${1}" in
     ;;
 
   *)
-    echo "Usage: fips-set <fips | fips_wifi | unset | status>"
+    echo "Usage: fips-set <fips | fips_wifi | unset | status>" >&2
     ;;
 esac
